/**
 * 稳定错误码：客户端按 code 翻译文案（packages/i18n），不解析 message。
 * HTTP 状态码只做大类区分，业务细节靠 code。
 */
export const ERROR_CODES = [
  // 通用
  'VALIDATION_FAILED',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'RATE_LIMITED',
  'INTERNAL',
  'SERVICE_UNAVAILABLE',
  // 房间
  'ROOM_FULL',
  'ROOM_CLOSED',
  'ROUND_ENDED',
  'ALREADY_IN_ROOM',
  'MEMBER_RESTRICTED',
  'SPONSORSHIP_REQUIRED',
  'FREE_ROOMS_EXHAUSTED',
  'TURN_PENDING',
  'QUEUE_FULL',
  'STATE_CONFLICT',
  'IDEMPOTENCY_CONFLICT',
  'EVENT_GAP',
  // 内容
  'CONTENT_UNAVAILABLE',
  'PUZZLE_UNPUBLISHED',
  'RATING_NOT_ALLOWED',
  // Jev
  'JEV_UNAVAILABLE',
  'JEV_BUSY',
  // 赞助
  'ORDER_EXPIRED',
  'PAYMENT_CHANNEL_UNAVAILABLE',
  'ORDER_STATE_CONFLICT',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

/** 错误码 → 默认 HTTP 状态码 */
export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  RATE_LIMITED: 429,
  INTERNAL: 500,
  SERVICE_UNAVAILABLE: 503,
  ROOM_FULL: 409,
  ROOM_CLOSED: 409,
  ROUND_ENDED: 409,
  ALREADY_IN_ROOM: 409,
  MEMBER_RESTRICTED: 403,
  SPONSORSHIP_REQUIRED: 403,
  FREE_ROOMS_EXHAUSTED: 403,
  TURN_PENDING: 409,
  QUEUE_FULL: 429,
  STATE_CONFLICT: 409,
  IDEMPOTENCY_CONFLICT: 409,
  EVENT_GAP: 410,
  CONTENT_UNAVAILABLE: 404,
  PUZZLE_UNPUBLISHED: 403,
  RATING_NOT_ALLOWED: 403,
  JEV_UNAVAILABLE: 503,
  JEV_BUSY: 429,
  ORDER_EXPIRED: 409,
  PAYMENT_CHANNEL_UNAVAILABLE: 503,
  ORDER_STATE_CONFLICT: 409,
};

/** 单人请求永远不返回赞助类错误（docs/rebuild/03-SPEC.md §6）。 */
export const SPONSORSHIP_CODES: ReadonlySet<string> = new Set(['SPONSORSHIP_REQUIRED', 'FREE_ROOMS_EXHAUSTED']);
